In [1]:
in_path = '/Users/pratyush/Downloads/liversegmentation/dicom_files/images'
out_path = '/Users/pratyush/Downloads/liversegmentation/output/images'

In [4]:
!which python

/opt/anaconda3/bin/python


In [18]:
from glob import glob
import shutil
import os
import dicom2nifti
import nibabel as nib
import numpy as np

In [16]:
!pip install nibabel

In [4]:
patient_list = glob(in_path+'/*')
patient_list.sort()
print(patient_list[0])

/Users/pratyush/Downloads/liversegmentation/dicom_files/images/liver_0


In [22]:
for patient in glob(in_path + '/*'):
    patient_name = os.path.basename(os.path.normpath(patient))
    number_folder = int(len(glob(patient+'/*'))/64)

    for i in range(number_folder):
        output_path_name = os.path.join(out_path,patient_name + '_' + str(i))
        os.mkdir(output_path_name)
        #print(output_path_name)
        for i ,file in enumerate(glob(patient+'/*')):
            if i == 64 + 1:
                break
            shutil.move(file,output_path_name)

/Users/pratyush/Downloads/liversegmentation/output/images/liver_9_0
/Users/pratyush/Downloads/liversegmentation/output/images/liver_9_1
/Users/pratyush/Downloads/liversegmentation/output/images/liver_9_2
/Users/pratyush/Downloads/liversegmentation/output/images/liver_9_3
/Users/pratyush/Downloads/liversegmentation/output/images/liver_9_4
/Users/pratyush/Downloads/liversegmentation/output/images/liver_9_5
/Users/pratyush/Downloads/liversegmentation/output/images/liver_9_6
/Users/pratyush/Downloads/liversegmentation/output/images/liver_9_7
/Users/pratyush/Downloads/liversegmentation/output/images/liver_7_0
/Users/pratyush/Downloads/liversegmentation/output/images/liver_7_1
/Users/pratyush/Downloads/liversegmentation/output/images/liver_7_2
/Users/pratyush/Downloads/liversegmentation/output/images/liver_7_3
/Users/pratyush/Downloads/liversegmentation/output/images/liver_7_4
/Users/pratyush/Downloads/liversegmentation/output/images/liver_7_5
/Users/pratyush/Downloads/liversegmentation/outp

In [13]:
in_path_images = '/Users/pratyush/Downloads/liversegmentation/output/images/*'
in_path_labels = '/Users/pratyush/Downloads/liversegmentation/output/labels/*'
out_path_images = '/Users/pratyush/Downloads/liversegmentation/nifti_files/images'
out_path_labels = '/Users/pratyush/Downloads/liversegmentation/nifti_files/labels'

list_images = glob(in_path_images)
list_images.sort()
list_labels = glob(in_path_labels)
list_labels.sort()
list_labels

['/Users/pratyush/Downloads/liversegmentation/output/labels/liver_0_0',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_10_0',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_10_1',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_10_2',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_10_3',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_10_4',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_10_5',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_10_6',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_11_0',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_11_1',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_11_2',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_11_3',
 '/Users/pratyush/Downloads/liversegmentation/output/labels/liver_11_4',
 '/Users/pratyush/Downloads/liversegmentation/output

In [14]:
import dicom2nifti.settings as settings

# Disable validation
settings.validate_slice_increment = False
settings.validate_orthogonal = False

for patient in list_labels:
    patient_name = os.path.basename(os.path.normpath(patient))
    dicom2nifti.dicom_series_to_nifti(patient,os.path.join(out_path_labels,patient_name+'.nii'))

In [22]:
input_nifti_file_path = '/Users/pratyush/Downloads/liversegmentation/nifti_files/labels/*'
list_labels = glob(input_nifti_file_path)
for patient in list_labels:
    nifti_file = nib.load(patient)
    fdata = nifti_file.get_fdata()
    print(fdata)
    np_unique = np.unique(fdata)
    if len(np_unique) == 1:
        print(patient)
        



[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
[[[0. 0. 0